### ISSUE TITLE
Add data from the API to the movie list (instead of just the title)

### ISSUE THREAD

**Issue by Bates550** [Bates550/movie-tracker#6]
- Store meta data from the API in `SearchBar`'s `onChange` before stripping everything but the title.
  - Maybe overwriting this `onChange` is sufficient for keeping the meta data from getting stale
- Add movie and its meta data to `state.movieList` in `SearchBar`'s `onSearch`.
  - May need to join `searchTerm` against the movie data titles.

**Comment by ycanastra** [comment]
Implemented by https://github.com/Bates550/movie-tracker/pull/7
